// GENERATED by @airun/compiler from content-pipeline.graph.ts — do not edit by hand.
// Round-trip fixture: confirms the IR→code path typechecks against @airun/sdk.

import { ai, defineWorkflow, state, step, tool, trigger, type Schema } from "../index.js";

// --- schemas ---
type Analysis = { "language": string; "tone": string; "keywords"?: string[] };
const Analysis: Schema<Analysis> = { parse: (x) => x as Analysis }; // TODO: validate at runtime
type CoreContent = { "title": string; "summary": string };
const CoreContent: Schema<CoreContent> = { parse: (x) => x as CoreContent }; // TODO: validate at runtime
type LandingContent = { "hero": string; "sections": string[] };
const LandingContent: Schema<LandingContent> = { parse: (x) => x as LandingContent }; // TODO: validate at runtime
type PricingContent = { "plans": { "name": string; "price": string }[] };
const PricingContent: Schema<PricingContent> = { parse: (x) => x as PricingContent }; // TODO: validate at runtime
type PageList = { "pages": { "slug": string; "title": string }[] };
const PageList: Schema<PageList> = { parse: (x) => x as PageList }; // TODO: validate at runtime
type PageContent = { "slug": string; "body": string };
const PageContent: Schema<PageContent> = { parse: (x) => x as PageContent }; // TODO: validate at runtime
type BriefPayload = { "productName": string; "audience": string; "description": string; "sources": string[] };
const BriefPayload: Schema<BriefPayload> = { parse: (x) => x as BriefPayload }; // TODO: validate at runtime
type Corpus = { "text": string; "sourceCount": number };
const Corpus: Schema<Corpus> = { parse: (x) => x as Corpus }; // TODO: validate at runtime

// --- tools ---
const groundSources = tool.http<Record<string, unknown>, Corpus>({
  id: "groundSources",
  name: "Ground the source material",
  method: "POST",
  url: "https://content.internal/api/ground",
  headers: { "Content-Type": "application/json" },
  body: (args) => args.sources,
  auth: { secret: "CONTENT_API_KEY" },
});

// --- state ---
const pages = state<unknown[]>("pages", { scope: "run", initial: [] });

export const contentPipeline = defineWorkflow({
  id: "wf_content_pipeline",
  name: "Content Pipeline",
  on: trigger.onWebhook({ path: "/hooks/content", method: "POST", schema: BriefPayload }),
  run: async ({ event }) => {
    const ground = await groundSources({ sources: event.sources });
    const analyze = await ai.generate({
      model: "claude-sonnet-4-6",
      system: "You analyze source material for tone and language.",
      prompt: `Analyze this corpus: ${ground.text}`,
      schema: Analysis,
    });
    const core = await ai.generate({
      model: "claude-sonnet-4-6",
      system: "You write the core title and summary.",
      prompt: `Write a title and summary for ${event.productName} in tone ${analyze.tone}`,
      schema: CoreContent,
    });
    const composeParts = await step.parallel([
      async () => {
        const landing = await ai.generate({
          model: "claude-sonnet-4-6",
          system: "You write the landing hero and sections.",
          prompt: `Write a landing section from this summary: ${core.summary}`,
          schema: LandingContent,
        });
        return landing;
      },
      async () => {
        const pricing = await ai.generate({
          model: "claude-sonnet-4-6",
          system: "You design pricing plans.",
          prompt: `Propose pricing plans for ${event.audience}`,
          schema: PricingContent,
        });
        return pricing;
      },
      async () => {
        const pageList = await ai.generate({
          model: "claude-sonnet-4-6",
          system: "You plan the list of pages the site needs.",
          prompt: `List the pages needed for ${event.productName}`,
          schema: PageList,
        });
        return pageList;
      },
    ]);
    const compose = { "landing": composeParts[0], "pricing": composeParts[1], "pageList": composeParts[2] };
    await step.forEach(compose.pageList.pages, async (page) => {
      const writePage = await ai.generate({
        model: "claude-sonnet-4-6",
        system: "You write the body for one page.",
        prompt: `Write the page titled ${page}`,
        schema: PageContent,
      });
      await pages.append(writePage);
    });
    const pagesValue = await pages.get();
    const assemble = step.transform(core, (input) => ({ title: core.title, landing: compose.landing, pricing: compose.pricing, pages: pagesValue }));
    return assemble;
  },
});
