// GENERATED by @airun/compiler from crm-assistant.graph.ts — do not edit by hand.
// Round-trip fixture: confirms the IR→code path typechecks against @airun/sdk.

import { ai, defineWorkflow, step, tool, trigger, type Schema } from "../index.js";
import { searchUnitsHandler } from "./crm-tools.js";

// --- schemas ---
type AssistResult = { "summary": string; "proposedChange": { "unitId": string; "patch": Record<string, unknown> } };
const AssistResult: Schema<AssistResult> = { parse: (x) => x as AssistResult }; // TODO: validate at runtime
type UserMessage = { "text": string; "workspaceId": string };
const UserMessage: Schema<UserMessage> = { parse: (x) => x as UserMessage }; // TODO: validate at runtime
type UpdateResult = { "unitId": string; "status": string };
const UpdateResult: Schema<UpdateResult> = { parse: (x) => x as UpdateResult }; // TODO: validate at runtime

// --- tools ---
const searchUnits = tool.fn({
  id: "searchUnits",
  name: "Search units",
  handler: searchUnitsHandler,
});
const updateUnit = tool.http<Record<string, unknown>, UpdateResult>({
  id: "updateUnit",
  name: "Update a unit",
  method: "PATCH",
  url: "https://crm.internal/api/units",
  headers: { "Content-Type": "application/json" },
  body: (args) => args.patch,
  auth: { secret: "CRM_TOKEN" },
});

export const crmAssistant = defineWorkflow({
  id: "wf_crm_assistant",
  name: "CRM Assistant",
  on: trigger.onWebhook({ path: "/hooks/assistant", method: "POST", schema: UserMessage }),
  run: async ({ event }) => {
    const route = await ai.classify({
      model: "claude-haiku-4-5-20251001",
      input: event.text,
      labels: ["Manage records", "Generate website", "Small talk"],
    });
    if (route === "Manage records") {
      const assist = await ai.agent({
        model: "claude-sonnet-4-6",
        system: "You help manage CRM records. Search before proposing a change.",
        prompt: event.text,
        tools: [searchUnits],
        stopWhen: { kind: "any", conditions: [{ kind: "noToolUse" }, { kind: "maxSteps", value: 8 }] },
        schema: AssistResult,
      });
      const approve = await step.approval({
        prompt: `Apply this change? ${assist.summary}`,
        timeout: "12h",
        onTimeout: "reject",
      });
      if (approve.approved) {
        const applyChange = await updateUnit({ patch: assist.proposedChange });
        return applyChange;
      } else {
        return {"status":"rejected"};
      }
    } else if (route === "Generate website") {
      const site = await ai.generate({
        model: "claude-sonnet-4-6",
        system: "You generate marketing copy.",
        prompt: event.text,
      });
      return site;
    } else if (route === "Small talk") {
      const chat = await ai.generate({
        model: "claude-haiku-4-5-20251001",
        system: "You are a friendly assistant.",
        prompt: event.text,
      });
      return chat;
    }
  },
});
