// GENERATED by @airun/compiler from invoice.graph.ts — do not edit by hand.
// Round-trip fixture: confirms the IR→code path typechecks against @airun/sdk.

import { ai, defineWorkflow, state, step, tool, trigger, type Schema } from "../index.js";

// --- schemas ---
type InvoiceData = { "total": number; "dueDate"?: string; "lineItems": { "description"?: string; "amount"?: number }[] };
const InvoiceData: Schema<InvoiceData> = { parse: (x) => x as InvoiceData }; // TODO: validate at runtime
type InvoicePayload = { "invoiceId": string; "vendor": string; "amount": number; "currency": string; "fileUrl": string };
const InvoicePayload: Schema<InvoicePayload> = { parse: (x) => x as InvoicePayload }; // TODO: validate at runtime
type LedgerResult = { "entryId": string; "status"?: string };
const LedgerResult: Schema<LedgerResult> = { parse: (x) => x as LedgerResult }; // TODO: validate at runtime

// --- tools ---
const postLedger = tool.http<Record<string, unknown>, LedgerResult>({
  id: "postLedger",
  name: "Post to ledger",
  method: "POST",
  url: "https://ledger.internal/api/entries",
  headers: { "Content-Type": "application/json" },
  body: (args) => args.data,
  auth: { secret: "LEDGER_API_KEY" },
});

// --- state ---
const processed = state<unknown[]>("processed", { scope: "persistent", initial: [] });

export const invoiceProcessing = defineWorkflow({
  id: "wf_invoice_processing",
  name: "Invoice Processing",
  on: trigger.onWebhook({ path: "/hooks/invoice", method: "POST", schema: InvoicePayload }),
  run: async ({ event }) => {
    const extract = await ai.generate({
      model: "claude-sonnet-4-6",
      system: "You extract structured data from invoices.",
      prompt: `Extract line items and totals from the invoice at ${event.fileUrl}`,
      schema: InvoiceData,
    });
    if (event.amount > 1000) {
      const approve = await step.approval({
        prompt: `Approve invoice ${event.invoiceId}?`,
        timeout: "24h",
        onTimeout: "reject",
      });
      if (approve.approved) {
        const postToLedger = await postLedger({ data: extract });
        await processed.append(event.invoiceId);
        return postToLedger;
      } else {
        return {"status":"rejected"};
      }
    } else {
      const postToLedger = await postLedger({ data: extract });
      await processed.append(event.invoiceId);
      return postToLedger;
    }
  },
});
