// GENERATED by @airun/compiler from landing.graph.ts — do not edit by hand.
// Round-trip fixture: confirms the IR→code path typechecks against @airun/sdk.

import { ai, defineWorkflow, state, step, tool, trigger, type Schema } from "../index.js";
import { finalizeSiteHandler, lintCheckHandler, writeComponentHandler } from "./site-tools.js";

// --- schemas ---
type SitePlan = { "title": string; "sections": { "heading": string; "body": string; "cta"?: string }[] };
const SitePlan: Schema<SitePlan> = { parse: (x) => x as SitePlan }; // TODO: validate at runtime
type BuildResult = { "entryPoint": string; "files": { "path": string; "contents": string }[] };
const BuildResult: Schema<BuildResult> = { parse: (x) => x as BuildResult }; // TODO: validate at runtime
type BriefPayload = { "productName": string; "tagline"?: string; "description": string; "audience": string; "brandColor"?: string };
const BriefPayload: Schema<BriefPayload> = { parse: (x) => x as BriefPayload }; // TODO: validate at runtime
type DeployResult = { "url": string; "deploymentId": string };
const DeployResult: Schema<DeployResult> = { parse: (x) => x as DeployResult }; // TODO: validate at runtime

// --- tools ---
const writeComponent = tool.fn({
  id: "writeComponent",
  name: "Write a site component",
  handler: writeComponentHandler,
});
const lintCheck = tool.fn({
  id: "lintCheck",
  name: "Lint the generated site",
  handler: lintCheckHandler,
});
const finalizeSite = tool.fn({
  id: "finalizeSite",
  name: "Finalize the build",
  handler: finalizeSiteHandler,
});
const deploySite = tool.http<Record<string, unknown>, DeployResult>({
  id: "deploySite",
  name: "Deploy to hosting",
  method: "POST",
  url: "https://deploy.internal/api/sites",
  headers: { "Content-Type": "application/json" },
  body: (args) => args.site,
  auth: { secret: "DEPLOY_TOKEN" },
});

// --- state ---
const deployments = state<unknown[]>("deployments", { scope: "persistent", initial: [] });

export const landingPageBuilder = defineWorkflow({
  id: "wf_landing_builder",
  name: "Landing Page Builder",
  on: trigger.onWebhook({ path: "/hooks/landing", method: "POST", schema: BriefPayload }),
  run: async ({ event }) => {
    const plan = await ai.generate({
      model: "claude-sonnet-4-6",
      system: "You are a senior landing-page designer.",
      prompt: `Draft a landing page for ${event.productName} aimed at ${event.audience}. Pitch: ${event.description}`,
      schema: SitePlan,
    });
    const build = await ai.agent({
      model: "claude-sonnet-4-6",
      system: "You implement the planned page as static files, then finalize.",
      prompt: `Implement this plan: ${plan}`,
      tools: [writeComponent, lintCheck, finalizeSite],
      stopWhen: { kind: "any", conditions: [{ kind: "toolCalled", tool: finalizeSite }, { kind: "maxSteps", value: 20 }] },
      schema: BuildResult,
    });
    const review = await step.approval({
      prompt: `Approve the landing page for ${event.productName}?`,
      timeout: "48h",
      onTimeout: "escalate",
    });
    if (review.approved) {
      const deploy = await deploySite({ site: build });
      await deployments.append(deploy.deploymentId);
      return deploy;
    } else {
      return {"status":"rejected"};
    }
  },
});
